-- List (year, ball_name, games) year, ball_name, and games are foreign keys
select * from list;

create table list (
games varchar (35) not null,
ball_name varchar(15) not null,
primary key (games, ball_name),
foreign key (games) references game_pair(games) on update cascade on delete cascade,
foreign key (ball_name) references pokeball(ball_name) on update cascade on delete cascade
);

insert into list values
('Sword and Shield', 'Poke Ball'),
('Sword and Shield', 'Great Ball'),
('Sword and Shield', 'Ultra Ball'),
('Sword and Shield', 'Premier Ball'),
('Sword and Shield', 'Nest Ball'),
('Sword and Shield', 'Heal Ball'),
('Sword and Shield', 'Net Ball'),
('Sword and Shield', 'Dusk Ball'),
('Sword and Shield', 'Dive Ball'),
('Sword and Shield', 'Timer Ball'),
('Sword and Shield', 'Repeat Ball'),
('Sword and Shield', 'Quick Ball'),
('Sword and Shield', 'Luxury Ball'),
('Sword and Shield', 'Level Ball'),
('Sword and Shield', 'Love Ball'),
('Sword and Shield', 'Moon Ball'),
('Sword and Shield', 'Dream Ball'),
('Sword and Shield', 'Heavy Ball'),
('Sword and Shield', 'Friend Ball'),
('Sword and Shield', 'Lure Ball'),
('Sword and Shield', 'Master Ball'),
('Sword and Shield', 'Beast Ball'),
('Sword and Shield', 'Fast Ball'),
('Sword and Shield', 'Sport Ball'),
('Sword and Shield', 'Safari Ball'),

('Brilliant Diamond and Shining Pearl', 'Poke Ball'),
('Brilliant Diamond and Shining Pearl', 'Premier Ball'),
('Brilliant Diamond and Shining Pearl', 'Great Ball'),
('Brilliant Diamond and Shining Pearl', 'Ultra Ball'),
('Brilliant Diamond and Shining Pearl', 'Master Ball'),
('Brilliant Diamond and Shining Pearl', 'Dive Ball'),
('Brilliant Diamond and Shining Pearl', 'Dusk Ball'),
('Brilliant Diamond and Shining Pearl', 'Heal Ball'),
('Brilliant Diamond and Shining Pearl', 'Luxury Ball'),
('Brilliant Diamond and Shining Pearl', 'Nest Ball'),
('Brilliant Diamond and Shining Pearl', 'Net Ball'),
('Brilliant Diamond and Shining Pearl', 'Quick Ball'),
('Brilliant Diamond and Shining Pearl', 'Repeat Ball'),
('Brilliant Diamond and Shining Pearl', 'Timer Ball'),
('Brilliant Diamond and Shining Pearl', 'Safari Ball'),
('Brilliant Diamond and Shining Pearl', 'Park Ball'),
('Brilliant Diamond and Shining Pearl', 'Cherish Ball'),

('Scarlet and Violet', 'Poke Ball'),
('Scarlet and Violet', 'Premier Ball'),
('Scarlet and Violet', 'Great Ball'),
('Scarlet and Violet', 'Ultra Ball'),
('Scarlet and Violet', 'Master Ball'),
('Scarlet and Violet', 'Nest Ball'),
('Scarlet and Violet', 'Heal Ball'),
('Scarlet and Violet', 'Repeat Ball'),
('Scarlet and Violet', 'Timer Ball'),
('Scarlet and Violet', 'Quick Ball'),
('Scarlet and Violet', 'Net Ball'),
('Scarlet and Violet', 'Luxury Ball'),
('Scarlet and Violet', 'Dive Ball'),
('Scarlet and Violet', 'Dusk Ball'),
('Scarlet and Violet', 'Beast Ball'),
('Scarlet and Violet', 'Dream Ball'),
('Scarlet and Violet', 'Lure Ball'),
('Scarlet and Violet', 'Heavy Ball'),
('Scarlet and Violet', 'Friend Ball'),
('Scarlet and Violet', 'Level Ball'),
('Scarlet and Violet', 'Fast Ball'),
('Scarlet and Violet', 'Love Ball'),
('Scarlet and Violet', 'Moon Ball');