-- Sandwich (sandwich_name, games, ingredients, effects) game_name is foreign key
select * from sandwich;

create table sandwich (
sandwich_name varchar(35) not null primary key,
games varchar(20) not null,
ingredients varchar(120) not null,
effects varchar(100) not null,
foreign key (games) references game_pair(games) on update cascade on delete cascade
);

delete from sandwich;

insert into sandwich values
('Jambon-Beurre', 'Scarlet and Violet', 'Ham, Butter', 'Encounter Power: Ground (Lv. 1), Raid Power: Ghost (Lv. 1), Catching Power: Bug (Lv. 1)'),
('Bitter Jambon-Beurre', 'Scarlet and Violet', 'Ham, Butter, Bitter Herba Mystica', 'Title Power: Ground (Lv. 2), Exp. Point Power: Ghost (Lv. 2), Encounter Power: Bug (Lv. 2)'),
('Sweet Jambon-Beurre', 'Scarlet and Violet', 'Ham, Butter, Sweet Herba Mystica', 'Title Power: Ground (Lv. 2), Egg Power (Lv. 2), Encounter Power: Bug (Lv. 2)'),
('Salty Jambon-Beurre', 'Scarlet and Violet', 'Ham, Butter, Salty Herba Mystica', 'Title Power: Ground (Lv. 2), Encounter Power: Ghost (Lv. 2), Raid Power: Bug (Lv. 2)'),
('Sour Jambon-Beurre', 'Scarlet and Violet', 'Ham, Butter, Sour Herba Mystica', 'Title Power: Ground (Lv. 2), Teensy Power: Ghost (Lv. 2), Encounter Power: Bug (Lv. 2)'),
('Spicy Jambon-Beurre', 'Scarlet and Violet', 'Ham, Butter, Spicy Herba Mystica', 'Title Power: Gound (Lv. 2), Humungo Power: Ghost (Lv. 2), Encounter Power: Bug (Lv. 2)'),
('Jam Sandwich', 'Scarlet and Violet', 'Strawberry, Jam', 'Catching Power: Fighting (Lv. 1), Item Drop Power: Psychic (Lv. 1), Egg Power (Lv. 1)'),
('Great Jam Sandwich', 'Scarlet and Violet', 'Strawberry, Jam, Yogurt', 'Catching Power: Fighting (Lv. 1), Item Drop Power: Psychic (Lv. 1), Raid Power: Ghost (Lv. 1)'),
('Ultra Jam Sandwich', 'Scarlet and Violet', 'Strawberry, Jam, Pineapple, Yogurt, Jam', 'Catching Power: Dark (Lv. 2), Item Drop Power: Ground (Lv. 2), Egg Power (Lv. 1)'),
('Master Jam Sandwich', 'Scarlet and Violet', 'Strawberry, Pineapple, Jam, Yogurt, Sweet Herba Mystica', 'Title Power: Dark (Lv. 2), Catching Power: Ground (Lv. 2), Item Drop Power: Fighting (Lv. 2)'),
('Pickle Sandwich', 'Scarlet and Violet', 'Pickle, Olive Oil', 'Teensy Power: Fighting (Lv. 1), Encounter Power: Fire (Lv. 1), Catching Power: Ghost (Lv. 1)'),
('Great Pickle Sandwich', 'Scarlet and Violet', 'Pickle, Watercress, Olive Oil', 'Item Drop Power: Fighting (Lv. 2), Encounter Power: Fire (Lv. 1), Catching Power: Ghost (Lv. 1)'),
('Ultra Pickle Sandwich', 'Scarlet and Violet', 'Pickle, Watercress, Basil, Olive Oil', 'Item Drop Power: Fighting (Lv. 2), Egg Power (Lv. 2), Catching Power: Fir (Lv. 1)'),
('Master Pickle Sandwich', 'Scarlet and Violet', 'Pickle, Watercress, Basil, Olive Oil, Sour Herba Mystica', 'Title Power: Fighting (Lv. 2), Teensy Power: Grass (Lv. 2), Egg Power (Lv. 2)'),
('Desert Sandwich', 'Scarlet and Violet', 'Apple x2, Yogurt, Whipped Cream', 'Catching Power: Flying (Lv. 1), Item Drop Power: Ice (Lv. 1), Egg Power (Lv. 1)'),
('Great Desert Sandwich', 'Scarlet and Violet', 'Apple x2, Kiwi, Yogurt, Whipped Cream', 'Catching Power: Flying (Lv. 2), Item Drop Power: Ice (Lv. 1), Egg Power (Lv. 1)'),
('Ultra Desert Sandwich', 'Scarlet and Violet', 'Apple x2, Kiwi, strawberry, Yogurt, Whipped Cream', 'Item Drop Power: Flying (Lv. 2), Catching Power: Ice (Lv. 2), Egg Power (Lv. 1)'),
('Master Desert Sandwich', 'Scarlet and Violet', 'Apple x2, Kiwi, Strawberry, Yogurt, Whipped Cream, Sweet Herba Mystica', 'Title Power: Flying (Lv. 2), Item Drop Power: Poison (Lv. 2), Catching Power: Fairy (Lv. 2)'),
('Avocado Sandwich', 'Scarlet and Violet', 'Avocado, Smoked Fillet, Salt', 'Exp. Point Power: Dragon (Lv. 1), Encounter Power: Electric (Lv. 1), Catching Power: Dark (Lv. 1)'),
('Great Avocado Sandwich', 'Scarlet and Violet', 'Avocado, Smoked Fillet, Tomato, Salt', 'Encounter Power: Dragon (Lv. 2), Catching Power: Fairy (Lv. 1), Exp. Point Power: Dark (Lv. 1)'),
('Ultra Avocado Sandwich', 'Scarlet and Violet', 'Avocado, Smoked Fillet, Tomato, Lettuce, Salt', 'Exp. Point Power: Grass (Lv. 2), Encounter Power: Dark (Lv. 2), Catching Power (Lv. 1)'),
('Master Avocado Sandwich', 'Scarlet and Violet', 'Avocado, Smoked Fillet, Tomato, Lettuce, Salt, Salty Herba Mystica', 'Title Power: Grass (Lv. 2), Exp. Point Power: Dark (Lv. 2), Encounter Power: Dragon (Lv. 2)'),
('Egg Sandwich', 'Scarlet and Violet', 'Egg, Cucumber, Salt, Mayonnaise', 'Encounter Power: Flying (Lv. 1), Exp. Point Power: Steel (Lv. 1), Raid Power: Rock (Lv. 1)'),
('Great Egg Sandwich', 'Scarlet and Violet', 'Egg, Cucumber, Red Onion, Salt, Mayonnaise', 'Encounter Power: Flying (Lv. 2), Exp. Point Power: Steel (Lv. 1), Raid Power: Rock (Lv. 1)'),
('Ultra Egg Sandwich', 'Scarlet and Violet', 'Egg, Cucumber, Red Onion, Cheese, Salt, Mayonnaise', 'Encounter Power: Flying (Lv. 2), Exp. Point Power: Steel (Lv. 2), Raid Power: Rock (Lv. 1)'),
('Master Egg Sandwich', 'Scarlet and Violet', 'Egg, Cucumber, Red Onion, Cheese, Salt, Mayonnaise, Salty Herba Mystica', 'Title Power: Flying (Lv. 2), Encounter Power: Rock (Lv. 2), Exp. Point Power: Normal (Lv. 2)'),
('Classic Bocadillo', 'Scarlet and Violet', 'Bacon, Cheese, Potato Tortilla, Olive Oil', 'Encounter Power: Ghost (Lv. 1), Catching Power: Grass (Lv. 1), Item Drop Power: Fire (Lv. 1)'),
('Great Classic Bocadillo Sandwich', 'Scarlet and Violet', 'Bacon, Cheese, Potato Tortilla, Olive Oil, Curry Powder', 'Humungo Power: Ghost (Lv. 2), Catching Power: Grass (Lv. 1), Encounter Power: Fire (Lv. 1)'),
('Ultra Classic Bocadillo Sandwich', 'Scarlet and Violet', 'Bacon, Cheese, Potato Tortilla, Avocado, Olive Oil, Curry Powder', 'Humungo Power: Dragon (Lv. 2), Catching Power: Fire (Lv. 2), Encounter Power: Ghost (Lv. 1)'),
('Master Classic Bocadilla', 'Scarlet and Violet', 'Bacon, Cheese, Potato Torilla, Avocado, Olive Oil, Curry Powder, Bitter Herba Mystica', 'Title Power: Dragon (Lv. 2), Item Drop Power: Ghost (Lv. 2), Catching Power: Normal (Lv. 2)'),
('BLT Sandwich', 'Scarlet and Violet', 'Bacon, Lettuce, Tomato, Mayonnaise, Mustard', 'Teensy Power: Rock (Lv. 1), Encounter Power: Fairy (Lv. 1), Catching Power: Grass (Lv. 1)'),
('Great BLT Sandwich', 'Scarlet and Violet', 'Bacon, Lettuce, Tomato, Basil, Mayonnaise, Mustard', 'Teensy Power: Grass (Lv. 2), Encounter Power: Rock (Lv. 2), Raid Power: Fairy (Lv. 1)'),
('Ultra BLT Sandwich', 'Scarlet and Violet', 'Bacon, Lettuce, Tomato, Basil, Cheese, Mayonnaise, Mustard', 'Teensy Power: Grass (Lv. 2), Encounter Power: Rock (Lv. 2), Catching Power: Fairy (Lv. 1)'),
('Master BLT Sandwich', 'Scarlet and Violet', 'Bacon, Lettuce, Tomato, Basil, Cheese, Mayonnaise, Mustard, Sweet Herba Mystica', 'Title Power: Grass (Lv. 2), Catching Power: Fairy (Lv. 2), Encounter Power: Normal (Lv. 2)'),
('Ham Sandwich', 'Scarlet and Violet', 'Pickle, Ham, Mayonnaise, Mustard', 'Teensy Power: FIghting (Lv. 1), Encounter Power: Normal (Lv. 1), Raid Power: Ground (Lv. 1)'),
('Great Ham Sandiwch', 'Scarlet and Violet', 'Pickle, Ham, Bacon, Mayonnaise, Mustard', 'Encounter Power: Fighting (Lv. 2), Catching Power: Flying (Lv. 1), Raid Power: Ground (Lv. 1)'),
('Ultra Ham Sandwich', 'Scarlet and Violet', 'Pickle, Ham, Bacon, Jalapeno, Mayonnaise, Mustard', 'Teensy Power: Rock (Lv. 2), Encounter Power: Fairy (Lv. 2), Catching Power: Grass (Lv. 1)'),
('Master Ham Sandwich', 'Scarlet and Violet', 'Pickle, Ham, Bacon, Jalapeno, Mayonnaise, Mustard, Salty Herba Mystica', 'Title Power: Rock (Lv. 2), Encounter Power: Fairy (Lv. 2), Catching Power: Grass (Lv. 2)'),
('Cheese Sandwich', 'Scarlet and Violet', 'Cheese, Cream Cheese, Pepper, Salt', 'Encounter Power: Bug (Lv. 1), Raid Power: Water (Lv. 1), Exp. Point Power: Steel (Lv. 1)'),
('Great Cheese Sandwich', 'Scarlet and Violet', 'Cheese, Avocado, Cream Cheese, Pepper, Salt', 'Encounter Power: Dragon (Lv. 2), Raid Power: Steel (Lv. 1), Exp. Point Power: Bug (Lv. 1)'),
('Ultra Cheese Sandwich', 'Scarlet and Violet', 'Cheese, Avocado, Basil, Cream Cheese, Pepper, Salt', 'Exp. Point Power: Dragon (Lv. 2), Raid Power: Electric (Lv. 2), Catching Power: Water (Lv. 1)'),
('Master Cheese Sandwich', 'Scarlet and Violet', 'Cheese, Avocado, Basil, Cream Cheese, Pepper, Salt, Salty Herba Mystica', 'Title Power: Dragon (Lv. 2), Exp. Point Power: Electric (Lv. 2), Raid Power: Water (Lv. 2)'),
('Hamburger Patty Sandwich', 'Scarlet and Violet', 'Hamburger, Onion, Vinegar, Pepper', 'Humungo Power: Pyshic (Lv. 1), Encounter Power: Dragon (Lv. 1), Catching Power: Steel (Lv. 1)'),
('Great Hamburger Patty Sandwich', 'Scarlet and Violet', 'Hamburger, Onion, Vinegar, Pepper, Horseradish', 'Humungo Power: Psychic (Lv. 2), Encounter Power: Dragon (Lv. 1), Catching Power: Steel (Lv. 1)'),
('Ultra Hamburger Sandwich', 'Scarlet and Violet', 'Hamburger, Onion, Watercress, Vinegar, Pepper, Horseradish', 'Humungo Power: Psychic (Lv. 2), Encounter Power: Dragon (Lv. 2), Catching Power: Steel (Lv. 1)'),
('Master Hamburger Sandwich', 'Scarlet and Violet', 'Hamburger, Onion, Watercress, Vinegar, Pepper, Horseradish, Sweet Herba Mystica', 'Title Power: Psychic (Lv. 2), Raid Power: Dragon (Lv. 2), Encounter Power: Steel (Lv. 2)'),
('Smoky Sandwich', 'Scarlet and Violet', 'Smoked Fillet, Watercress, Vinegar, Pepper, Salt', 'Exp. Point Power: Dark (Lv. 1), Raid Power: Dragon (Lv. 1), Encounter Power: Psychic (Lv. 1)'),
('Great Smoky Sandwich', 'Scarlet and Violet', 'Smoked Fillet, Watercress, Red Onion, Vinegar, Pepper, Salt', 'Exp. Point Power: Ghost (Lv. 2), Raid Power: Psychic (Lv. 1), Encounter Power: Dark (Lv. 1)'),
('Ultra Smoky Sandwich', 'Scarlet and Violet', 'Smoked Fillet, Watercress, Red Onion, Basil, Vinegar, Pepper, Salt', 'Exp. Point Power: Dark (Lv. 2), Raid Power: Psychic (Lv. 2), Encounter Power: Ghost (Lv. 1)'),
('Master Smoky Sandwich', 'Scarlet and Violet', 'Smoked Fillet, Watercress, Red Onion, Basil, Vinegar, Pepper, Salt, Salty Herba Mystica', 'Title Power: Dark (Lv. 2), Exp. Point Power: Psychic (Lv. 2), Raid Power: Ghost (Lv. 2)'),
('Variety Sandwich', 'Scarlet and Violet', 'Bacon, Tomato, Smoked Fillet, Salt, Vinegar', 'Teensy Power: Flying (Lv. 1), Encounter Power: Dark (Lv. 1), Catching Power: Bug (Lv. 1)'),
('Great Variety Sandwich', 'Scarlet and Violet', 'Bacon, Tomato, Smoked Fillet, Potato Salad, Salt, Vinegar', 'Teensy Power: Bug (Lv. 2), Encounter Power: Dragon (Lv. 1), Catching Power: Dark (Lv. 1)'),
('Ultra Variety Sandwich', 'Scarlet and Violet', 'Bacon, Tomato, Smoked Fillet, Potato Salad, Hamburger, Salt, Vinegar', 'Encounter Power: Bug (Lv. 2), Catching Power: Dark (Lv. 2), Humungo Power: Steel (Lv. 1)'),
('Master Variety Sandwich', 'Scarlet and Violet', 'Bacon, Tomato, Smoked Fillet, Potato Salad, Hamburger, Salt, Vinegar, Bitter Herba Mystica', 'Title Power: Bug (Lv. 2), Exp. Point Power: Steel (Lv. 2), Encounter Power: Normal (Lv. 2)'),
('Sweet Sandwich', 'Scarlet and Violet', 'Banana, Apple, Cheese, Whipped Cream, Butter', 'Egg Power (Lv. 1), Item Drop Power: Bug (Lv. 1), Raid Power: Flying (Lv. 1)'),
('Great Sweet Sandwich', 'Scarlet and Violet', 'Banana, Apple, Cheese, Whipped Cream, Butter, Salt', 'Egg Power (Lv. 2), Item Drop Power: Bug (Lv. 1), Raid Power: Flying (Lv. 1)'),
('Ultra Sweet Sandwich', 'Scarlet and Violet', 'Banana, Apple, Cheese, Basil, Whipped Cream, Butter, Salt', 'Egg Power (Lv. 2), Item Drop Power: Flying (Lv. 2), Raid Power: Normal (Lv. 1)'),
('Master Sweet Sandwich', 'Scarlet and Violet', 'Banana, Apple, Cheese, Basil, Whipped Cream, Butter, Salt, Sour Herba Mystica', 'Title Power: Electric (Lv. 2), Catching Power: Normal (Lv. 2), Item Drop Power: Fighting (Lv. 2)'),
('Five-Alarm Sandwich', 'Scarlet and Violet', 'Chorizo, Onion, Green Bell Pepper, Mustard, Ketchup, Pepper', 'Humungo Power: Poison (Lv. 1), Exp. Point Power: Normal (Lv. 1), Raid Power: Dragon (Lv. 1)'),
('Great Five-Alarm Sandwich', 'Scarlet and Violet', 'Chorizo, Onion, Green Bell Pepper, Basil, Mustard, Ketchup, Pepper', 'Humungo Power: Poison (Lv. 2), Raid Power: Fire (Lv. 1), Exp. Point Power: Dragon (Lv. 1)'),
('Ultra Five-Alarm Sandwich', 'Scarlet and Violet', 'Chorizo, Onion, Green Bell Pepper, Basil, Jalapeno, Mustard, Ketchup, Pepper', 'Humungo Power: Poison (Lv. 2), Raid Power: Fire (Lv. 2), Exp. Point Power: Dragon (Lv. 1)'),
('Master Five-Alarm Sandwich', 'Scarlet and Violet', 'Chorizo, Onion, Green Bell Pepper, Basil, Jalapeno, Mustard, Ketchup, Pepper, Spicy Herba Mystica', 'Title Power: Dragon (Lv. 2), Humungo Power: Dragon (Lv. 2), Raid Power: Normal (Lv. 2)'),
('Potato Salad Sandwich', 'Scarlet and Violet', 'Potato Salad, Cucumber, Red Bell Pepper, Mayonnaise', 'Teensy Power: Bug (Lv. 1), Encounter Power: Steel (Lv. 1), Catching Power: Ghost (Lv. 1)'),
('Great Potato Salad', 'Scarlet and Violet', 'Potato Salad, Cucumber, Red Bell Pepper, Avocado, Mayonnaise', 'Catching Power: Dragon (Lv. 2), Encounter Power: Ghost (Lv. 1), Humungo Power: Bug (Lv. 1)'),
('Ultra Potato Salad', 'Scarlet and Violet', 'Potato Salad, Cucumber, Red Bell Pepper, Avocado, Red Onion, Mayonnaise', 'Catching Power: Ghost (Lv. 2), Encounter Power: Bug (Lv. 2), Humungo Power: Dragon (Lv. 1)'),
('Master Potato Salad Sandwich', 'Scarlet and Violet', 'Potato Salad, Cucumber, Red Bell Pepper, Avocado, Red Onion, Mayonnaise, Sweet Herba Mystica', 'Title Power: Ghost (Lv. 2), Catching Power: Dragon (Lv. 2), Encounter Power: Normal (Lv. 2)'),
('Marmalade Sandwich', 'Scarlet and Violet', 'Cheese, Marmalade', 'Item Drop Power: Fighting (Lv. 1), Catching Power: Rock (Lv. 1), Egg Power (Lv. 1)'),
('Great Marmalade Sandwich', 'Scarlet and Violet', 'Cheese, Marmalade, Butter', 'Egg Power (Lv. 2), Raid Power: Rock (Lv. 1), Item Drop: Poison (Lv. 1)'),
('Ultra Marmalade Sandwich', 'Scarlet and Violet', 'Cheese, Marmalade, Butter, Yogurt', 'Egg Power (Lv. 2), Item Drop Power: Poison (Lv. 2), Raid Power: Fighting (Lv. 1)'),
('Master Marmalade Sandwich', 'Scarlet and Violet', 'Cheese, Marmalade, Butter, Yogurt, Salty Herba Mystica', 'Title Power: Bug (Lv. 2), Encounter Power: Poison (Lv. 2), Item Drop Power: Fighting (Lv. 2)'),
('Peanut Butter Sandwich', 'Scarlet and Violet', 'Banana, Peanut Butter', 'Egg Power (Lv. 1), Item Drop Power: Electric (Lv. 1), Raid Power: Bug (Lv. 1)'),
('Great Peanut Butter Sandwich', 'Scarlet and Violet', 'Banana, Peanut Butter, Butter', 'Egg Power (Lv. 2), Raid Power: Electric (Lv. 2), Exp. Point Power: Normal (Lv. 1)'),
('Ultra Peanut Butter Sandwich', 'Scarlet and Violet', 'Banana, Peanut Butter, Butter, Jam', 'Egg Power (Lv. 2), Raid Power: Normal (Lv. 2), Item Drop Power: Bug (Lv. 1)'),
('Master Peanut Butter Sandwich', 'Scarlet and Violet', 'Banana, Peanut Butter, Butter, Jam, Spicy Herba Mystica', 'Title Power: Electric (Lv. 2), Raid Power: Normal (Lv. 2), Item Drop Power: Bug (Lv. 2)'),
('Noodle Sandwich', 'Scarlet and Violet', 'Noodles, Olive Oil, Ketchup', 'Encounter Power: Poison (Lv. 1), Raid Power: Rock (Lv. 1), Humungo Power: Ground (Lv. 1)'),
('Great Noodle Sandwich', 'Scarlet and Violet', 'Noodles, Lettuce, Olive Oil, Ketchup', 'Encounter Power: Poison (Lv. 2), Humungo Power: Rock (Lv. 1), Raid Power: Ground (Lv. 1)'),
('Ultra Noodle Sandwich', 'Scarlet and Violet', 'Noodles, Lettuce, Chorizo, Olive Oil, Ketchup', 'Encounter Power: Poison (Lv. 2), Exp. Point Power: Fire (Lv. 2), Humungo Power: Electric (Lv. 1)'),
('Master Noodle Sandwich', 'Scarlet and Violet', 'Noodles, Lettuce, Chorizo, Olive Oil, Ketchup, Bitter Herba Mystica', 'Title Power: Poison (Lv. 2), Exp. Point Power: Electric (Lv. 2), Encounter Power: Normal (Lv. 2)'),
('Fried Fillet Sandwich', 'Scarlet and Violet', 'Fried Fillet, Potato Salad, Mayonnaise, Ketchup', 'Teensy Power: Bug (Lv. 1), Raid Power: Dark (Lv. 1), Exp. Point Power: Steel (Lv. 1)'),
('Great Fried Fillet Sandwich', 'Scarlet and Violet', 'Fried Fillet, Potato Salad, Lettuce, Mayonnaise, Ketchup', 'Teensy Power: Bug (Lv. 2), Raid Power: Dark (Lv. 1), Catching Power: Steel (Lv. 1)'),
('Ultra Fried Fillet Sandwich', 'Scarlet and Violet', 'Fried Fillet, Potato Salad, Lettuce, Mayonnaise, Ketchup, Horseradish', 'Teensy Power: Bug (Lv. 2), Raid Power: Dark (Lv. 2), Encounter Power: Steel (Lv. 1)'),
('Master Fried Fillet Sandwich', 'Scarlet and Violet', 'Fried Fillet, Potato Salad, Lettuce, Mayonnaise, Ketchup, Horseradish, Spicy Herba Mystica', 'Title Power: Bug (Lv. 2), Humungo Power: Steel (Lv. 2), Raid Power: Normal (Lv. 2)'),
('Fruit Sandwich', 'Scarlet and Violet', 'Banana, Apple, Pineapple, Kiwi, Whipped Cream', 'Item Drop Power: Normal (Lv. 1), Catching Power: Ground (Lv. 1), Egg Power (Lv. 1)'),
('Great Fruit Sandwich', 'Scarlet and Violet', 'Banana, Apple, Pineapple, Kiwi, Whipped Cream, Marmalade', 'Item Drop Power: Normal (Lv. 2), Catching Power: Poison (Lv. 1), Egg Power (Lv. 1)'),
('Ultra Fruit Sandwich', 'Scarlet and Violet', 'Banana, Apple, Pineapple, Kiwi, Whipped Cream, Marmalade, Yogurt', 'Item Drop Power: Normal (Lv. 2), Catching Power: Poison (Lv. 2), Egg Power (Lv. 1)'),
('Master Fruit Sandwich', 'Scarlet and Violet', 'Banana, Apple, Pineapple, Kiwi, Whipped Cream, Marmalade, Yogurt, Sweet Herba Mystica', 'Title Power: Normal (Lv. 2), Item Drop Power: Poison (Lv. 2), Catching Power: Flying (Lv. 2)'),
('Hefty Sandwich', 'Scarlet and Violet', 'Potato Tortilla, Fried Fillet, Bacon, Potato Salad, Salt, Peanut Butter', 'Encounter Power: Steel (Lv. 1), Raid Power: Ghost (Lv. 1), Catching Power: Bug (Lv. 1)'),
('Great Hefty Sandwich', 'Scarlet and Violet', 'Potato Tortilla, Fried Fillet, Bacon, Potato Salad, Herbed Sausage, Salt, Peanut Butter', 'Encounter Power: Ghost (Lv. 2), Raid Power: Psychic (Lv. 2), Catching Power: Dark (Lv. 1)'),
('Ultra Hefty Sandwich', 'Scarlet and Violet', 'Potato Tortilla, Fried Fillet, Bacon, Potato Salad, Herbed Sausage, Hamburger, Salt, Peanut Butter', 'Title Power: Ghost (Lv. 2), Teensy Power: Dark (Lv. 2), Catching Power: Normal (Lv. 2)'),
('Master Hefty Sandwich', 'Scarlet and Violet', 'Potato Tortilla, Fried Fillet, Bacon, Potato Salad, Herbed Sausage, Hamburger, Salt, Peanut Butter, Salty Herba Mystica', ''),
('Tofu Sandwich', 'Scarlet and Violet', 'Tofu x2, Rice, Lettuce, Avocado, Horseradish, Salt', 'Encounter Power: Normal (Lv. 1), Egg Power: Lvl. 1), Catching Power, Grass (Lv. 1)'),
('Great Tofu Sandwich', 'Scarlet and Violet', 'Tofu x2, Rice, Lettuce, Avocado, Horseradish, Wasabi, Salt, Horseradish', 'Encounter Power: Normal (Lv. 2), Raid Power: Fighting (Lv. 1), Catching Power: Grass (Lv. 1)'),
('Ultra Tofu Sandwich', 'Scarlet and Violet', 'Tofu x2, Rice, Lettuce, Avocado, Watercress, Wasabi, Salt, Horseradish', 'Raid Power: Normal (Lv. 2), Encounter Power: Fighting (Lv. 2), Catching Power: Grass (Lv. 1)'),
('Master Tofu Sandwich', 'Scarlet and Violet', 'Tofu x2, Rice, Lettuce, Avocado, Watercress, Wasabi, Salt, Horseradish, Salty Herba Mystica', 'Title Power: Normal (Lv. 2), Encounter Power: Grass (Lv. 2), Catching Power: Fighting (Lv. 2)'),
('Herbed Sausage Sandwich', 'Scarlet and Violet', 'Herbed Sausage, Ketchup', 'Encounter Power: Fighting (Lv. 1), Exp. Point Power: Ghost (Lv. 1), Raid Power: Ground (Lv. 1)'),
('Great Herbed Sausage', 'Scarlet and Violet', 'Herbed Sausage, Ketchup, Mustard', 'Encounter Power: Ground (Lv. 2), Exp. Point Power: Ghost (Lv. 1), Raid Power: Fighting (Lv. 1)'),
('Ultra Herbed Sausage', 'Scarlet and Violet', 'Herbed Sausage, Lettuce, Ketchup, Mustard', 'Exp. Point Power: Ground (Lv. 2), Raid Power: Ghost (Lv. 2), Encounter Power: Fighting (Lv. 1)'),
('Legendary Herbed Sausage Sandwich', 'Scarlet and Violet', 'Herbed Sausage, Lettuce, Ketchup, Mustard, Bitter Herba Mystica', 'Title Power: Ground (Lv. 2), Exp. Point Power: Fighting (Lv. 2), Raid Power: Normal (Lv. 2)'),
('Curry-and-Rice-Style Sandwich', 'Scarlet and Violet', 'Rice, Curry Powder, Mayonnaise', 'Humungo Power: Normal (Lv. 1), Encounter Power: Fire (Lv. 1), Raid Power: Fighting (Lv. 1)'),
('Great Curry-and-Rice-Style Sandwich', 'Scarlet and Violet', 'Rice, Jalapeno, Curry Powder, Mayonnaise', 'Humungo Power: Grass (Lv. 2), Encounter Power: Fighting (Lv. 1), Item Drop Power: Normal (Lv. 1)'),
('Ultra Curry-and-Rice-Style Sandwich', 'Scarlet and Violet', 'Rice, Jalapeno, Tomato, Curry Powder, Mayonnaise', 'Humungo Power: Grass (Lv. 2), Encounter Power: Normal (Lv. 2), Item Drop Power: Fairy (Lv. 1)'),
('Master Curry-and-Rice Sandwich', 'Scarlet and Violet', 'Rice, Jalapeno, Tomato, Curry Powder, Mayonnaise, Spicy Herba Mystica', 'Title Power: Grass (Lv. 2), Humungo Power: Fairy (Lv. 2), Encounter Power: Normal (Lv. 2)'),
('Zesty Sandwich', 'Scarlet and Violet', 'Jalapeno, Onion, Herbed Sausage', 'Humungo Power: Psychic (Lv. 1), Exp. Pointer Power: Fighting (Lv. 1), Encounter Power: Water (Lv. 1)'),
('Great Zesty Sandwich', 'Scarlet and Violet', 'Jalapeno, Onion, Herbed Sausage, Green Bell Pepper', 'Humungo Power: Pysychic (Lv. 2), Encounter Power: Fighting (Lv. 1), Exp. Point Power: Water (Lv. 1)'),
('Ultra Zesty Sandwich', 'Scarlet and Violet', 'Jalapeno, Onion, Herbed Sausage, Green Bell Pepper, Watercress', 'Humungo Power: Psychic (Lv. 2), Encounter Power: Ground (Lv. 2), Exp. Point Power: Fighting (Lv. 1)'),
('Master Zesty Sandwich', 'Scarlet and Violet', 'Jalapeno, Onion, Herbed Sausage, Green Bell Pepper, Watercress, Sour Herba Mystica', 'Title Power: Psychic (Lv. 2), Teensy Power: Fighting (Lv. 2), Encounter Power: Normal (Lv. 2)'),
('Refreshing Sandwich', 'Scarlet and Violet', 'Tomato, Avocado, Horseradish, Salt', 'Catching Power: Bug (Lv. 1), Encounter Power: Fighting (Lv. 1), Raid Power: Dragon (Lv. 1)'),
('Great Refreshing Sandwich', 'Scarlet and Violet', 'Tomato, Avocado, Kiwi, Marmalade, Salt', 'Catching Power: Dragon (Lv. 2), Encounter Power: Fire (Lv. 1), Item Drop Power: Poison (Lv. 1)'),
('Ultra Refreshing Sandwich', 'Scarlet and Violet', 'Tomato, Avocado, Kiwi, Pickle, Marmalade, Salt', 'Catching Power: Dragon (Lv. 2), Encounter Power: Fighting (Lv. 2), Item Drop Power: Poisons (Lv. 1)'),
('Master Refreshing Sandwich', 'Scarlet and Violet', 'Tomtato, Avocado, Kiwi, Pickle, Marmalade, Salt, Spicy Herba Mystica', 'Title Power: Dragon (Lv. 2), Humungo Power: Poison (Lv. 2), Encounter Power: Normal (Lv. 2)'),
('Spicy-Sweet Sandwich', 'Scarlet and Violet', 'Hamburger, Tomato, Kiwi, Pineapple, Butter, Horseradish', 'Catching Power: Poison (Lv. 1), Encounter Power: Fire (Lv. 1), Item Drop Power: Ground (Lv. 1)'),
('Great Spicy-Sweet Sandwich', 'Scarlet and Violet', 'Hamburger, Tomato, Kiwi, Avocado, Pineapple, Butter, Horseradish', 'Catching Power: Dragon (Lv. 2), Encounter Power: Ground (Lv. 1), Item Drop Power: Poison (Lv. 1)'),
('Ultra Spicy-Sweet Sandwich', 'Scarlet and Violet', 'Hamburger, Tomato, Kiwi, Pineapple, Avocado, Cheese, Butter, Horseradish', 'Catching Power: Dragon (Lv. 2), Encounter Power: Ground (Lv. 2), Item Drop Power: Poison (Lv. 1)'),
('Master Spicy-Sweet Sandwich', 'Scarlet and Violet', 'Hamburger, Tomato, Kiwi, Pineapple, Avocado, Cheese, Butter, Horseradish, Bitter Herba Mystica', 'Title Power: Dragon (Lv. 2), Item Drop Power: Poison (Lv. 2), Encounter Power: Normal (Lv. 2)'),
('Curry-and-Noodle Sandwich', 'Scarlet and Violet', 'Noodles, Red Bell Pepper, Bacon, Yellow Bell Pepper, Olive Oil, Salt, Pepper', 'Exp. Point Power: Electric (Lv. 1), Encounter Power: Psychic (Lv. 1), Catching Power: Rock (Lv. 1)'),
('Great Curry-and-Noodle Sandwich', 'Scarlet and Violet', 'Noodles, Red Bell Pepper, Bacon, Yellow Bell Pepper, Jalapeno, Olive Oil, Salt, Pepper', 'Item Drop Power: Rock (Lv. 2), Encounter Power: Psychic (Lv. 1), Catching Power: Electric (Lv. 1)'),
('Ultra Curry-and-Noodle Sandwich', 'Scarlet and Violet', 'Noodles, Red Bell Pepper, Bacon, Jalapeno, Egg, Olive Oil, Salt, Pepper', 'Exp. Point Power: Rock (Lv. 2), Encounter Power: Grass (Lv. 2), Catching Power: Ice (Lv. 1)'),
('Master Curry-and-Noodle Sandwich', 'Scarlet and Violet', 'Noodles, Red Bell Pepper, Bacon, Jalapeno, Egg, Olive Oil, Salt, Pepper, Sweet Herba Mystica', 'Title Power: Rock (Lv. 2), Egg Power (Lv. 2), Encounter Power: Normal (Lv. 2)'),
('Tower Sandwich', 'Scarlet and Violet', 'Hamburger, Noodles, Potato Salad, Rice, Olive Oil, Salt, Pepper', 'Exp. Point Power: Steel (Lv. 1), Encounter Power: Fire (Lv. 1), Humungo Power: Ghost (Lv. 1)'),
('Great Tower Sandwich', 'Scarlet and Violet', 'Hamburger, Noodles, Potato Salad, Rice, Klawf Stick, Olive Oil, Salt Pepper', 'Exp. Point Power: Steel (Lv. 2), Encounter Power: Ghost (Lv. 1), Humungo Power: Ice (Lv. 1)'),
('Ultra Tower Sandwich', 'Scarlet and Violet', 'Hamburger, Noodles, Potato Salad, Rice, Klawf Stick, Tofu, Olive Oil, Salt, Pepper', 'Encounter Power: Steel (Lv. 2), Humungo Power: Ice (Lv. 2), Catching Power: Normal (Lv. 1)'),
('Master Tower Sandwich', 'Scarlet and Violet', 'Hamburger, Noodles, Potato Salad, Rice, Klawf Stick, Tofu, Olive Oil, Salt, Pepper, Bitter Herba Mystica', 'Title Power: Steel (Lv. 2), Encounter Power: Normal (Lv. 2), Exp. Point Power: Fighting (Lv. 2)'),
('Vegetable Sandwich', 'Scarlet and Violet', 'Green Bell Pepper, Tomato, Cucumber, Salt, Olive Oil, Vinegar', 'Teensy Power: Poison (Lv. 1), Encounter Power: Water (Lv. 1), Catching Power: Bug (Lv. 1)'),
('Great Vegetable Sandwich', 'Scarlet and Violet', 'Green Bell Pepper, Tomato, Cucumber, Red Onion, Salt, Olive Oil, Vinegar', 'Encounter Power: Ghost (Lv. 2), Teensy Power: Bug (Lv. 1), Catching Power: Poison (Lv. 1)'),
('Ultra Vegetable Sandwich', 'Scarlet and Violet', 'Green Bell Pepper, Tomato, Cucumber, Red Onion, Watercress, Salt, Olive Oil, Vinegar', 'Encounter Power: Ghost (Lv. 2), Teensy Power: Bug (Lv. 2), Catching Power: Poison (Lv. 1)'),
('Master Vegetable Sandwich', 'Scarlet and Violet', 'Green Bell Pepper, Tomato, Cucumber, Red Onion, Salt, Olive Oil, Vinegar, Herba Mystica', 'Title Power: Ghost (Lv. 2), Encounter Power: Bug (Lv. 2), Catching Power: Poison (Lv. 2)'),
('Klawf Claw Sandwich', 'Scarlet and Violet', 'Klawf Stick, Tomato, Lettuce, Salt, Olive Oil', 'Encounter Power: Grass (Lv. 1), Catching Power: Fairy (Lv. 1), Item Drop Power: Ice'),
('Great Klawf Claw Sandwich', 'Scarlet and Violet', 'Klawf Stick, Tomato, Lettuce, Salt, Olive Oil, Wasabi', 'Encounter Power: Grass (Lv. 2), Catching Power: Fairy (Lv. 1), Item Drop Power: Ice (Lv. 1)'),
('Ultra Klawf Claw Sandwich', 'Scarlet and Violet', 'Klawf Stick, Tomato, Lettuce, Yellow Bell Pepper, Salt, Olive Oil, Wasabi', 'Encounter Power: Grass (Lv. 2), Catching Power: Ice (Lv. 2), Item Drop Power: Electric (Lv. 1)'),
('Master Klawf Claw Sandwich', 'Scarlet and Violet', 'Klawf Stick, Tomato, Lettuce, Yellow Bell Pepper, Salt, Olive Oil, Wasabi, Spicy Herba Mystica', 'Title Power: Grass (Lv. 2), Humungo Power: Ice (Lv. 2), Encounter Power: Electric (Lv. 2)'),
('Decadent Sandwich', 'Scarlet and Violet', 'Smoked Fillet, Klawf Stick, Watercress, Basil, Vinegar, Olive Oil, Salt', 'Exp. Point Power: Ice (Lv. 1), Raid Power: Psychic (Lv. 1), Encounter Power: Dark (Lv. 1)'),
('Great Decadent Sandwich', 'Scarlet and Violet', 'Smoked Fillet, Klawf Stick, Watercress, Basil, Tofu, Vinegar Olive Oil, Salt', 'Exp. Point Power: Ice (Lv. 2), Encounter Power: Normal (Lv. 1), Catching Power: Dark (Lv. 1)'),
('Ultra Decadent Sandwich', 'Scarlet and Violet', 'Smoked Fillet, Klawf Stick, Watercress, Basil, Tofu, Red Onion, Vinegar, Olive Oil, Salt', 'Exp. Point Power: Ghost (Lv. 2), Encounter Power: Dark (Lv. 2), Catching Power: Ice (Lv. 1)'),
('Master Decadent Sandwich', 'Scarlet and Violet', 'Smoked Fillet, Klawf Stick, Watercress, Basil, Tofu, Red Onion, Vinegar, Olive Oil, Salt, Spicy Herba Mystica', 'Title Power: Ghost (Lv. 2), Humungo Power: Dark (Lv. 2), Encounter Power: Ice (Lv. 2)'),
('Legendary Bitter Sandwich', 'Scarlet and Violet', 'Lettuce, Bacon, Bitter Herba Mystica, Pepper', 'Title Power: Rock (Lv. 2), Exp. Point Power: Ice (Lv. 2), Encounter Power: Grass (Lv. 2)'),
('Legendary Salty Sandwich', 'Scarlet and Violet', 'Lettuce, Bacon, Salty Herba Mystica, Pepper', 'Title Power: Rock (Lv. 2), Exp. Point Power: Ice (Lv. 2), Encounter Power: Grass (Lv. 2)'),
('Legendary Sweet Sandwich', 'Scarlet and Violet', 'Lettuce, Bacon, Sweet Herba Mystica, Pepper', 'Title Power: Rock (Lv. 2), Egg Power (Lv. 2), Encounter Power: Grass (Lv. 2)'),
('Legendary Sour Sandwich', 'Scarlet and Violet', 'Lettuce, Bacon, Sour Herba Mystica, Pepper', 'Title Power: Rock (Lv. 2), Teensy Power: Ice (Lv. 2), Encounter Power: Grass (Lv. 2)'),
('Legendary Spicy Sandwich', 'Scarlet and Violet', 'Lettuce, Bacon, Spicy Herba Mystica, Pepper', 'Title Power: Rock (Lv. 2), Humungo Power: Ice (Lv. 2), Encounter Power: Grass (Lv. 2)'),
('Tropical Sandwich', 'Scarlet and Violet', 'Klawf Stick, Avocado, Marmalade', 'Egg Power (Lv. 1), Encounter Power: Fairy (Lv. 1), Catching Power: Dragon (Lv. 1)'),
('Great Tropical Sandwich', 'Scarlet and Violet', 'Klawf Stick, Avocado, Pineapple, Marmalade', 'Catching Power: Ground (Lv. 2), Encounter Power: Dark (Lv. 1), Item Drop Power: Water (Lv. 1)'),
('Ultra Tropical Sandwich', 'Scarlet and Violet', 'Klawf Stick, Avocado, Pineapple, Jalapeno, Marmalade', 'Catching Power: Rock (Lv. 2), Item Drop Power: Water (Lv. 2), Encounter Power: Ground (Lv. 1)'),
('Master Tropical Sandwich', 'Scarlet and Violet', 'Klawf Stick, Avocado, Pineapple, Jalapeno, Marmalade, Sour Herba Mystica', 'Title Power: Rock (Lv. 2), Catching Power: Water (Lv. 2), Item Drop Power: Ground (Lv. 2)'),
('Sushi Sandwich', 'Scarlet and Violet', 'Rice, Smoked Fillet x2, Klawf Stick, Salt, Vinegar, Wasabi', 'Encounter Power: Dark (Lv. 1), Catching Power: Fighting (Lv. 1), Humungo Power: Normal (Lv. 1)'),
('Great Sushi Sandwich', 'Scarlet and Violet', 'Rice, Smoked Fillet x2, Klawf Stick, Watercress, Salt, Vinegar, Wasabi', 'Exp. Point Power: Dark (Lv. 2), Encounter Power: Fighting (Lv. 1), Catching Power: Normal (Lv. 1)'),
('Ultra Sushi Sandwichj', 'Scarlet and Violet', 'Rice, Smoked Fillet x2, Klawf Stick x2, Watercress, Salt, Vinegar, Wasabi', 'Encounter Power: Ice (Lv. 2), Catching Power: Normal (Lv. 2), Humungo Power: Darkl (Lv. 1)'),
('Master Sushi Sandwich', 'Scarlet and Violet', 'Rice, Smoked Fillet x2, Klawf Stick x2, Watercress, Salt, Vinegar, Wasabi, Sour Herba Mystica', 'Title Power: Ice (Lv. 2), Teensy Power: Dark (Lv. 2), Encounter Power: Normal (Lv. 2)'),
('Nouveau Veggie Sandwich', 'Scarlet and Violet', 'Watercress, Yellow Bell Pepper, Onion, Tomato, Olive Oil, Wasabi', 'Item Drop Power: Electric (Lv. 1), Encounter Power: Fairy (Lv. 1), Catching Power: Psychic (Lv. 1)'),
('Great Nouveau Veggie Sandwich', 'Scarlet and Violet', 'Watercress, Yellow Bell Pepper, Onion, Tomato, Cucumber, Olive Oil, Wasabi', 'Item Drop Power: Electric (Lv. 2), Encounter Power: Fairy (Lv. 1), Catching Power: Psychic (Lv. 1)'),
('Ultra Nouveau Veggie Sandwich', 'Scarlet and Violet', 'Watercress, Yellow Bell Pepper, Onion, Tomato, Cucumber, Olive Oil, Wasabi, Mayonnaise', 'Teensy Power: Electric (Lv. 2), Encounter Power: Fairy (Lv. 2), Catching Power: Psychic (Lv.1)'),
('Master Nouveau Veggie Sandwich', 'Scarlet and Violet', 'Watercress, Yellow Bell Pepper, Onion, Tomato, Cucumber, Olive Oil, Wasabi, Mayonnaise, Sweet Herba Mystica', 'Title Power: Electric (Lv. 2), Catching Power: Fairy (Lv. 2), Encounter Power: Psychic (Lv. 2)');
